# Wild camping spots for Ireland, compiled 2026-08 from Reddit (r/WildCampingIreland,
# r/irishtourism) and blog research. Coordinates are initial estimates to be
# sanity-checked against Nominatim.
#
# type: beach | lake | mountain | forest | island | coast | trail | river
# access: hike | walk | drive   (hike = proper walk-in, walk = short stroll, drive = park beside)
SPOTS = [
    # ---- WICKLOW ----
    dict(name="Lough Ouler", county="Wicklow", type="lake", access="hike", lat=53.0333, lng=-6.3661,
         desc="The famous heart-shaped corrie lake below Tonelagee. Hike up from the Wicklow Gap road; pitch on the grassy shore and watch the sun rise over the rim.",
         src=["https://www.reddit.com/r/WildCampingIreland/", "https://wanderlog.com/place/details/1584524/lough-ouler"],
         hike_km=2.5),
    dict(name="Lough Dan", county="Wicklow", type="lake", access="hike", lat=53.0730, lng=-6.2530,
         desc="Quiet ribbon lake tucked between soft green hills below Scarr. Approach from the Oldbridge side; sandy beach at the north end is a classic pitch.",
         src=["https://theirishinsider.ie/wanderlist/travel-in-ireland/wild-camping-ireland/"],
         hike_km=3.0),
    dict(name="Glenmalure – Baravore", county="Wicklow", type="forest", access="walk", lat=52.9930, lng=-6.4180,
         desc="Ireland's longest glacial valley. Popular grassy flats near the ford and hostel at Baravore; busy summer weekends, quieter midweek.",
         src=["https://www.reddit.com/r/WildCampingIreland/comments/1l3699m/wild_camping_in_wicklow/"],
         hike_km=0.5),
    dict(name="Fraughan Rock Glen", county="Wicklow", type="mountain", access="hike", lat=52.9860, lng=-6.4370,
         desc="Hanging valley above Glenmalure with waterfalls spilling down granite slabs. A short steep pull from Baravore rewards with real seclusion.",
         src=["https://www.reddit.com/r/WildCampingIreland/comments/1l3699m/wild_camping_in_wicklow/"],
         hike_km=1.5),
    dict(name="Upper Lough Bray", county="Wicklow", type="lake", access="walk", lat=53.1720, lng=-6.3320,
         desc="Moody corrie lake under Kippure, minutes from the Old Military Road. Room for a small tent; handy first-timer spot close to Dublin.",
         src=["https://www.reddit.com/r/WildCampingIreland/comments/1l3699m/wild_camping_in_wicklow/"],
         hike_km=0.8),
    dict(name="Glensoulan Valley", county="Wicklow", type="river", access="hike", lat=53.1580, lng=-6.2530,
         desc="Sheltered valley on the Dargle above Powerscourt Waterfall. Park at Crone Woods, cross Maulin and drop to the bridge — pitch by the river.",
         src=["https://www.reddit.com/r/WildCampingIreland/comments/1l3699m/wild_camping_in_wicklow/"],
         hike_km=4.0),
    dict(name="Cloghoge Valley (Lough Tay)", county="Wicklow", type="lake", access="hike", lat=53.1080, lng=-6.2440,
         desc="The dark 'Guinness lake' below Luggala. Camp discreetly in the valley between Lough Tay and Lough Dan — private estate, so leave zero trace.",
         src=["https://www.reddit.com/r/WildCampingIreland/comments/1l3699m/wild_camping_in_wicklow/"],
         hike_km=2.0),
    dict(name="Devil's Glen Woods", county="Wicklow", type="forest", access="walk", lat=53.0060, lng=-6.1210,
         desc="Deep wooded gorge on the Vartry with waterfall walk. Sheltered pitches under the trees; a favourite for low-key overnights.",
         src=["https://www.reddit.com/r/WildCampingIreland/comments/1trwb7v/first_wild_camping_trip_in_wicklow_looking_for/"],
         hike_km=1.0),
    dict(name="Brittas Bay (south cove)", county="Wicklow", type="beach", access="walk", lat=52.8720, lng=-6.0530,
         desc="Sheltered sandy cove at the quiet end of Brittas Bay's dunes. Park and wander down a track to a windbreak of marram grass.",
         src=["https://www.reddit.com/r/WildCampingIreland/comments/1trwb7v/first_wild_camping_trip_in_wicklow_looking_for/"],
         hike_km=0.6),
    dict(name="Blessington Lakes – Baltyboys", county="Wicklow", type="lake", access="walk", lat=53.1440, lng=-6.5140,
         desc="Little beaches along the Poulaphouca shoreline from Baltyboys car park. ESB land — arrive after 7pm, gone early, no fires.",
         src=["https://www.reddit.com/r/WildCampingIreland/comments/1gj0b90/favourite_area_to_wild_camp_within_23_hours_of/"],
         hike_km=1.2),
    dict(name="Djouce – White Hill saddle", county="Wicklow", type="mountain", access="hike", lat=53.1330, lng=-6.2560,
         desc="High saddle on the Wicklow Way boardwalk with huge views over Lough Tay and the Irish Sea. Exposed — pick a calm night.",
         src=["https://www.reddit.com/r/WildCampingIreland/comments/1uwmvrx/handy_one_in_galway/"],
         hike_km=3.0),
    dict(name="Lugnaquilla (Camarahill shoulder)", county="Wicklow", type="mountain", access="hike", lat=52.9670, lng=-6.4650,
         desc="Leinster's highest summit. High camps off the Camarahill route from Fenton's pub car park; serious weather, serious views.",
         src=["https://www.reddit.com/r/WildCampingIreland/"],
         hike_km=5.0),
    dict(name="Glenmacnass Valley", county="Wicklow", type="river", access="walk", lat=53.0500, lng=-6.3300,
         desc="Waterfall, granite slabs and open moor at the top of the Military Road above Laragh. Easy access, wild feel.",
         src=["https://theirishinsider.ie/wanderlist/travel-in-ireland/wild-camping-ireland/"],
         hike_km=0.7),
    # ---- KERRY ----
    dict(name="Ventry Beach dunes", county="Kerry", type="beach", access="walk", lat=52.1220, lng=-10.3620,
         desc="Long crescent of sand near Dingle with grassy dune pockets out of the wind. Village pub and shop a stroll away.",
         src=["https://www.reddit.com/r/WildCampingIreland/comments/1uvmhk5/kerry_cant_be_beat/"],
         hike_km=0.5),
    dict(name="Wine Strand, Smerwick Harbour", county="Kerry", type="beach", access="walk", lat=52.1830, lng=-10.4110,
         desc="Small sandy coves around Smerwick Harbour on the Dingle peninsula, backed by grass patches perfect for a small tent.",
         src=["https://www.reddit.com/r/WildCampingIreland/comments/1uvmhk5/kerry_cant_be_beat/"],
         hike_km=0.3),
    dict(name="Coumeenoole Beach", county="Kerry", type="beach", access="walk", lat=52.1080, lng=-10.4600,
         desc="Slea Head's dramatic cove framed by cliffs — Star Wars country. Grassy ledges above the strand; can be very windy.",
         src=["https://www.irelandbeforeyoudie.com/top-10-best-spots-for-wild-camping-in-ireland-ranked/"],
         hike_km=0.4),
    dict(name="Inch Beach dunes", county="Kerry", type="beach", access="walk", lat=52.1410, lng=-9.9770,
         desc="Five kilometres of spit and dune between Dingle Bay and Castlemaine Harbour. Walk beyond the crowds and disappear behind a dune.",
         src=["https://www.reddit.com/r/WildCampingIreland/comments/1uvmhk5/kerry_cant_be_beat/"],
         hike_km=1.5),
    dict(name="Great Blasket Island", county="Kerry", type="island", access="hike", lat=52.0910, lng=-10.5250,
         desc="Boat from Dunquin, then camp above the deserted village looking back at the mainland. Seals on An Trá Bhán below. Check crossings ahead.",
         src=["https://www.reddit.com/r/WildCampingIreland/comments/1v6ggyt/campsite_recommendations/"],
         hike_km=1.0),
    dict(name="Derrynane dunes & Abbey Island", county="Kerry", type="beach", access="walk", lat=51.7590, lng=-10.1360,
         desc="Golden sand, monastic ruins and dune hollows near Caherdaniel on the Ring of Kerry. Abbey Island is walkable at low tide.",
         src=["https://www.reddit.com/r/WildCampingIreland/comments/1toko4c/camping_near_kerry_light_reserve/"],
         hike_km=0.8),
    dict(name="Lamb's Head", county="Kerry", type="coast", access="drive", lat=51.7370, lng=-10.1120,
         desc="Quiet cul-de-sac road south of Caherdaniel with grassy lay-bys right on the water. Stunning Kenmare Bay views, superb dark skies.",
         src=["https://www.reddit.com/r/WildCampingIreland/comments/1toko4c/camping_near_kerry_light_reserve/"],
         hike_km=0.1),
    dict(name="Ballinskelligs Beach", county="Kerry", type="beach", access="walk", lat=51.8230, lng=-10.2770,
         desc="Beach, pier and ruined abbey in the heart of the Kerry Dark Sky Reserve. Milky Way over the Atlantic on a clear night.",
         src=["https://www.reddit.com/r/WildCampingIreland/comments/1toko4c/camping_near_kerry_light_reserve/"],
         hike_km=0.4),
    dict(name="Minard Castle", county="Kerry", type="coast", access="drive", lat=52.1230, lng=-10.1110,
         desc="Ruined castle above a storm beach of giant sandstone boulders. Grassy patches for tents; a dramatic, easy overnight.",
         src=["https://www.dreambigtravelfarblog.com/blog/wild-camping-spots-ireland"],
         hike_km=0.2),
    dict(name="Brandon Creek", county="Kerry", type="coast", access="drive", lat=52.2740, lng=-10.3350,
         desc="The narrow inlet where St Brendan set sail. Flat ground by the pier under Mount Brandon's flank; big cliff walks either side.",
         src=["https://www.dreambigtravelfarblog.com/blog/wild-camping-spots-ireland"],
         hike_km=0.2),
    dict(name="Mount Brandon (Faha side)", county="Kerry", type="mountain", access="hike", lat=52.2340, lng=-10.2540,
         desc="Ireland's holiest mountain. High camps on the Faha ridge route above Cloghane give paternoster lakes and ocean views.",
         src=["https://theirishinsider.ie/wanderlist/travel-in-ireland/wild-camping-ireland/"],
         hike_km=3.5),
    dict(name="Molls Gap", county="Kerry", type="mountain", access="drive", lat=51.9560, lng=-9.6540,
         desc="High pass between Kenmare and Killarney on the Ring of Kerry. Van-friendly pull-ins with views over the Gap of Dunloe country.",
         src=["https://www.dreambigtravelfarblog.com/blog/wild-camping-spots-ireland"],
         hike_km=0.0),
    dict(name="Black Valley (Kerry Way)", county="Kerry", type="trail", access="hike", lat=51.9740, lng=-9.7300,
         desc="Remote valley behind the Gap of Dunloe on the Kerry Way — one of the last places in Ireland to get electricity. Classic through-hiker camp.",
         src=["https://www.reddit.com/r/WildCampingIreland/comments/1vf39vg/on_the_kerry_way/"],
         hike_km=2.0),
    # ---- CORK ----
    dict(name="Allihies (Ballydonegan Bay)", county="Cork", type="beach", access="walk", lat=51.6410, lng=-10.0440,
         desc="Copper-mine village on the Beara Way with a quartz-sand beach and painted pubs. Pitches in the grass above the strand.",
         src=["https://www.irelandbeforeyoudie.com/top-10-best-spots-for-wild-camping-in-ireland-ranked/"],
         hike_km=0.3),
    dict(name="Castletownbere pier", county="Cork", type="coast", access="drive", lat=51.6510, lng=-9.9110,
         desc="Six free first-come motorhome spots by Ireland's biggest whitefish port. 24-hour public toilets nearby and great pubs (MacCarthy's).",
         src=["https://www.dreambigtravelfarblog.com/blog/wild-camping-spots-ireland"],
         hike_km=0.0),
    dict(name="Beara Way – Dursey Sound", county="Cork", type="trail", access="hike", lat=51.6130, lng=-10.1970,
         desc="Wind-scoured end of the Beara Peninsula by the cable car to Dursey Island. Wild coastal camping on the Beara Way loop.",
         src=["https://www.reddit.com/r/WildCampingIreland/comments/1u4n2bq/seeking_advice_on_identifying_suitable_spots_to/"],
         hike_km=1.0),
    # ---- WATERFORD ----
    dict(name="Coumshingaun Lough", county="Waterford", type="lake", access="hike", lat=52.2280, lng=-7.5680,
         desc="One of Europe's finest corrie lakes, walled by 350m Comeragh cliffs. Steep 45-minute pull from the R676; pitch by the outflow.",
         src=["https://www.reddit.com/r/WildCampingIreland/top/"],
         hike_km=1.8),
    dict(name="Trá na mBó", county="Waterford", type="beach", access="walk", lat=52.1420, lng=-7.3480,
         desc="Hidden Copper Coast cove near Bunmahon reached by a grassy track. Sea stacks, caves and hardly a soul.",
         src=["https://www.reddit.com/r/WildCampingIreland/"],
         hike_km=0.5),
    dict(name="Ballyquin Beach", county="Waterford", type="beach", access="drive", lat=51.9720, lng=-7.7160,
         desc="Quiet strand north of Ardmore with parking right behind the beach and views along the cliffs. Handy van overnight.",
         src=["https://www.dreambigtravelfarblog.com/blog/wild-camping-spots-ireland"],
         hike_km=0.1),
    dict(name="Bunmahon dunes", county="Waterford", type="beach", access="walk", lat=52.1380, lng=-7.3660,
         desc="Surf beach on the Copper Coast backed by dunes; village chipper and pub two minutes away.",
         src=["https://www.dreambigtravelfarblog.com/blog/wild-camping-spots-ireland"],
         hike_km=0.2),
    # ---- TIPPERARY ----
    dict(name="The Vee & Bay Lough", county="Tipperary", type="mountain", access="drive", lat=52.2830, lng=-7.9560,
         desc="Hairpin pass through the Knockmealdowns ablaze with rhododendron in early summer. Park at the Vee; Bay Lough is a short walk below.",
         src=["https://www.dreambigtravelfarblog.com/blog/wild-camping-spots-ireland"],
         hike_km=0.6),
    dict(name="Borheen Lough (Galtees)", county="Tipperary", type="lake", access="hike", lat=52.3560, lng=-8.1830,
         desc="Lonely corrie lake tucked under Galtymore's southern cliffs. A proper hike-in earns you the whole mountain to yourself.",
         src=["https://www.reddit.com/r/WildCampingIreland/"],
         hike_km=3.0),
    dict(name="Lake Muskry (Galtees)", county="Tipperary", type="lake", access="hike", lat=52.3760, lng=-8.1130,
         desc="Corrie lake in the Galtees above the Glen of Aherlow, reached by forest track from Rossadrehid. Sheltered grassy shore.",
         src=["https://www.reddit.com/r/WildCampingIreland/"],
         hike_km=4.0),
    # ---- GALWAY ----
    dict(name="Dog's Bay & Gurteen Bay", county="Galway", type="beach", access="walk", lat=53.3810, lng=-9.9540,
         desc="Back-to-back horseshoe beaches of pure white shell sand near Roundstone. Camp in the machair between the two.",
         src=["https://www.reddit.com/r/WildCampingIreland/comments/1v6ggyt/campsite_recommendations/"],
         hike_km=0.5),
    dict(name="Omey Island", county="Galway", type="island", access="walk", lat=53.5350, lng=-10.1530,
         desc="Tidal island near Claddaghduff — drive or walk across the sand at low tide. Check tide times or enjoy an unplanned long stay.",
         src=["https://www.irelandbeforeyoudie.com/top-10-best-spots-for-wild-camping-in-ireland-ranked/"],
         hike_km=1.2),
    dict(name="Gleninagh Valley (Twelve Bens)", county="Galway", type="mountain", access="hike", lat=53.5210, lng=-9.8330,
         desc="Raw glacial valley into the heart of the Twelve Bens. For experienced campers; rocky, boggy and utterly wild.",
         src=["https://theirishinsider.ie/wanderlist/travel-in-ireland/wild-camping-ireland/"],
         hike_km=3.5),
    dict(name="Lough Corrib shore (near Cong)", county="Galway", type="lake", access="walk", lat=53.5252, lng=-9.3051,
         desc="Lakeside woodland clearing on Corrib's western shore near Cong — a Reddit-shared favourite with a morning-swim spot.",
         src=["https://www.reddit.com/r/WildCampingIreland/comments/1uwmvrx/handy_one_in_galway/"],
         hike_km=0.8),
    # ---- MAYO ----
    dict(name="Rinroe Beach, Carrowteige", county="Mayo", type="beach", access="walk", lat=54.3310, lng=-9.8290,
         desc="Remote north Mayo strand below the Children of Lir loop walks. Sea stacks, cliffs, and wind — bring good pegs.",
         src=["https://www.reddit.com/r/irishtourism/comments/1efm85i/seeking_wild_camping_spots_in_county_mayo_or/"],
         hike_km=0.4),
    dict(name="Keem Bay, Achill", county="Mayo", type="beach", access="walk", lat=53.9670, lng=-10.1940,
         desc="Achill's amphitheatre cove below Croaghaun. Arrive late, leave early — it's mobbed by day, magical by night.",
         src=["https://www.irelandbeforeyoudie.com/top-10-best-spots-for-wild-camping-in-ireland-ranked/"],
         hike_km=0.5),
    dict(name="Wild Nephin – Letterkeen", county="Mayo", type="forest", access="hike", lat=54.0180, lng=-9.5540,
         desc="Ireland's only official wilderness backpacking area and a gold-tier Dark Sky Park. Camp along the Letterkeen loop near the Brogan Carroll bothy.",
         src=["https://theirishinsider.ie/wanderlist/travel-in-ireland/wild-camping-ireland/"],
         hike_km=2.5),
    dict(name="Silver Strand (Dooaghtry)", county="Mayo", type="beach", access="hike", lat=53.7050, lng=-9.9110,
         desc="White horseshoe beach south of Louisburgh framed by Mweelrea. Dune camping with Croagh Patrick on the horizon.",
         src=["https://secretireland.ie/ultimate-guide-to-wild-camping-spots-in-ireland-explore-the-best-of-nature/"],
         hike_km=0.6),
    # ---- SLIGO ----
    dict(name="Easkey Castle", county="Sligo", type="coast", access="drive", lat=54.2890, lng=-8.9630,
         desc="Ruined 13th-century tower beside one of Europe's best surf reefs. Grassy foreshore where locals and surfers camp all summer.",
         src=["https://www.reddit.com/r/irishtourism/comments/1efm85i/seeking_wild_camping_spots_in_county_mayo_or/"],
         hike_km=0.1),
    dict(name="Mullaghmore Head", county="Sligo", type="coast", access="drive", lat=54.4700, lng=-8.4530,
         desc="Big-wave headland with Classiebawn Castle and Benbulben behind. Grassy verges on the loop road; very exposed in a blow.",
         src=["https://www.irelandbeforeyoudie.com/top-10-best-spots-for-wild-camping-in-ireland-ranked/"],
         hike_km=0.2),
    # ---- DONEGAL ----
    dict(name="Mullaghderg Beach", county="Donegal", type="beach", access="drive", lat=55.0090, lng=-8.4210,
         desc="Rosses strand near Kincasslagh loved by locals. Big parking area behind the beach; Atlantic sunsets straight off the sand.",
         src=["https://www.dreambigtravelfarblog.com/blog/wild-camping-spots-ireland"],
         hike_km=0.2),
    dict(name="Dunree Beach & Fort", county="Donegal", type="beach", access="walk", lat=55.1970, lng=-7.5510,
         desc="Sheltered Inishowen cove beneath the old fort on Lough Swilly. Park up top and carry the tent down to the sand.",
         src=["https://theirishinsider.ie/wanderlist/travel-in-ireland/wild-camping-ireland/"],
         hike_km=0.3),
    dict(name="Silver Strand, Malin Beg", county="Donegal", type="beach", access="hike", lat=54.6660, lng=-8.7790,
         desc="Perfect horseshoe at the end of the Glencolmcille road, reached down 174 steps. Carry everything in; sunsets are worth it.",
         src=["https://secretireland.ie/ultimate-guide-to-wild-camping-spots-in-ireland-explore-the-best-of-nature/"],
         hike_km=0.5),
    dict(name="Tramore Beach, Dunfanaghy", county="Donegal", type="beach", access="hike", lat=55.1720, lng=-7.8620,
         desc="Wild back strand reached through big dunes from Horn Head bridge — 25 minutes' walk keeps the crowds away entirely.",
         src=["https://secretireland.ie/ultimate-guide-to-wild-camping-spots-in-ireland-explore-the-best-of-nature/"],
         hike_km=1.8),
    dict(name="Bluestack Mountains (Lough Eske side)", county="Donegal", type="mountain", access="hike", lat=54.7280, lng=-8.0420,
         desc="Granite wilderness at the start of the Bluestack Way above Lough Eske. Corrie lakes, zero crowds, proper remoteness.",
         src=["https://www.reddit.com/r/WildCampingIreland/comments/1qxv9wz/looking_for_a_3_day_hike/"],
         hike_km=3.0),
    dict(name="Sliabh Liag (Slieve League)", county="Donegal", type="coast", access="hike", lat=54.6390, lng=-8.6790,
         desc="Among Europe's highest sea cliffs. Camp back from the edge off the Pilgrim's Path for a sunset you won't forget.",
         src=["https://secretireland.ie/ultimate-guide-to-wild-camping-spots-in-ireland-explore-the-best-of-nature/"],
         hike_km=2.0),
    # ---- DOWN ----
    dict(name="Blue Lough, Mournes", county="Down", type="lake", access="hike", lat=54.1580, lng=-5.9640,
         desc="Corrie lake under Slieve Binnian's tors in the Annalong Valley — the Mournes' classic first wild camp. Park at Carrick Little.",
         src=["https://www.reddit.com/r/irishtourism/comments/nejzjv/wild_camping_in_ireland/"],
         hike_km=3.0),
    dict(name="Slieve Donard col", county="Down", type="mountain", access="hike", lat=54.1800, lng=-5.9270,
         desc="High saddle beside the Mourne Wall below Northern Ireland's highest peak. Watch the lights of Newcastle come on far below.",
         src=["https://www.reddit.com/r/irishtourism/comments/nejzjv/wild_camping_in_ireland/"],
         hike_km=4.0),
    # ---- LAOIS/OFFALY ----
    dict(name="Glenbarrow (Slieve Blooms)", county="Laois", type="forest", access="walk", lat=53.1030, lng=-7.5820,
         desc="Waterfalls on the young River Barrow with beginner-friendly wild camping along the Slieve Bloom Way. Gentle and green.",
         src=["https://www.reddit.com/r/WildCampingIreland/comments/1qxv9wz/looking_for_a_3_day_hike/"],
         hike_km=1.0),
    # ---- CARLOW ----
    dict(name="Barrow Way – St Mullins", county="Carlow", type="trail", access="walk", lat=52.4890, lng=-6.9290,
         desc="Grassy towpath camping where the Barrow turns tidal below the monastic village. Canoe-tourer and bikepacker favourite.",
         src=["https://www.reddit.com/r/WildCampingIreland/comments/1u4n2bq/seeking_advice_on_identifying_suitable_spots_to/"],
         hike_km=0.4),
    # ---- LEITRIM ----
    dict(name="Lough Gill shore", county="Leitrim", type="lake", access="drive", lat=54.2500, lng=-8.3480,
         desc="Lay-by overnight on the lake of Yeats's Isle of Innisfree. An easy, scenic van stop between Sligo and Dromahair.",
         src=["https://www.dreambigtravelfarblog.com/blog/wild-camping-spots-ireland"],
         hike_km=0.0),
    # ---- CAVAN ----
    dict(name="Mullagh Lough", county="Cavan", type="lake", access="drive", lat=53.8110, lng=-6.9560,
         desc="Reedy fishing lake with picnic tables and bins by the shore. Low-drama lakeside overnight in drumlin country; midges in July.",
         src=["https://www.dreambigtravelfarblog.com/blog/wild-camping-spots-ireland"],
         hike_km=0.0),
    # ---- WEXFORD ----
    dict(name="Baginbun Beach", county="Wexford", type="beach", access="walk", lat=52.1750, lng=-6.8290,
         desc="Where the Normans landed in 1170. Red sandstone headland, sheltered sand, and sunrise-to-sunset light on the Hook.",
         src=["https://www.dreambigtravelfarblog.com/blog/wild-camping-spots-ireland"],
         hike_km=0.3),
    dict(name="Hook Head", county="Wexford", type="coast", access="drive", lat=52.1240, lng=-6.9290,
         desc="Beside the world's oldest working lighthouse. Van parking on the limestone shelf; whales pass in autumn.",
         src=["https://www.dreambigtravelfarblog.com/blog/wild-camping-spots-ireland"],
         hike_km=0.1),
    # ---- LIMERICK ----
    dict(name="Kilteery Pier", county="Limerick", type="coast", access="drive", lat=52.6110, lng=-9.1710,
         desc="Sleepy Shannon-estuary pier with picnic tables and evening swimmers. Ask locally and you'll be left in peace.",
         src=["https://www.dreambigtravelfarblog.com/blog/wild-camping-spots-ireland"],
         hike_km=0.0),
    # ---- CORK (deep dive) ----
    dict(name="Barleycove Beach dunes", county="Cork", type="beach", access="walk", lat=51.4710, lng=-9.7080,
         desc="West Cork's finest strand, backed by a wandering dune system near Mizen Head. Cross the pontoon bridge and lose yourself behind a dune.",
         src=["https://www.theirishroadtrip.com/camping-in-cork/", "https://irelandindepth.com/a-guide-to-camping-in-cork-ireland/"],
         hike_km=0.8),
    dict(name="Three Castle Head", county="Cork", type="coast", access="hike", lat=51.4890, lng=-9.7770,
         desc="Medieval towers above a black lake on 100m cliffs at Mizen's wildest corner. Private farmland — ask at the farm and tread gently.",
         src=["https://www.westcorkdiscovered.com/blog/three-castle-head"],
         hike_km=1.5),
    dict(name="Sheep's Head ridge (Seefin)", county="Cork", type="trail", access="hike", lat=51.5830, lng=-9.6800,
         desc="Overnight on the hilly spine of the Sheep's Head Way with Bantry Bay on one side and Dunmanus on the other. Out toward Kilcrohane and back.",
         src=["https://www.ukclimbing.com/forums/hill_talk/wild_camp_-_cork-672420"],
         hike_km=3.0),
    dict(name="Lough Hyne", county="Cork", type="lake", access="walk", lat=51.5010, lng=-9.2980,
         desc="Europe's first marine nature reserve — a saltwater lake that glows with bioluminescence on dark summer nights. Kayak in or pitch discreetly above the shore.",
         src=["https://irelandindepth.com/a-guide-to-camping-in-cork-ireland/"],
         hike_km=0.4),
    dict(name="Gougane Barra", county="Cork", type="forest", access="walk", lat=51.8400, lng=-9.3260,
         desc="St Finbarr's island chapel on a mirror-still lake ringed by forested crags. Camping isn't allowed in the park itself — pitch up the Keimaneigh side and walk in.",
         src=["https://irelandindepth.com/a-guide-to-camping-in-cork-ireland/"],
         hike_km=0.8),
    dict(name="Sherkin Island", county="Cork", type="island", access="hike", lat=51.4660, lng=-9.4180,
         desc="Ferry from Baltimore, then wander past the abbey to Silver Strand for an island night with Roaringwater Bay all around. Two pubs for the evening.",
         src=["https://irelandindepth.com/a-guide-to-camping-in-cork-ireland/"],
         hike_km=2.0),
    dict(name="Inchydoney Beach", county="Cork", type="beach", access="walk", lat=51.5940, lng=-8.8680,
         desc="Blue Flag surf beach on its own little island near Clonakilty. Dune pockets at the quiet eastern end, away from the hotel side.",
         src=["https://irelandindepth.com/a-guide-to-camping-in-cork-ireland/"],
         hike_km=0.5),
    # ---- NORTHERN IRELAND ----
    dict(name="Chimney Rock (Bloody Bridge)", county="Down", type="mountain", access="hike", lat=54.1750, lng=-5.9030,
         desc="From Bloody Bridge car park a 30-minute pull leads onto Chimney Rock Mountain — sea views to the Isle of Man. Camp behind the summit boulders out of the wind.",
         src=["https://outdoorscott.com/wild-camping-northern-ireland/", "https://www.reddit.com/r/northernireland/comments/1mev0gb/wild_camping_spots/"],
         hike_km=2.5),
    dict(name="Annalong Wood", county="Down", type="forest", access="hike", lat=54.1520, lng=-5.9380,
         desc="Pine shelter partway up the Annalong Valley — the Mournes' classic sheltered wildcamp when the tops are blowing a hoolie.",
         src=["https://www.mourne-mountains.com/mournes/staying-in-the-mournes/wild-camp-spots/"],
         hike_km=2.0),
    dict(name="Rostrevor Forest (Kodak Corner)", county="Down", type="forest", access="hike", lat=54.0950, lng=-6.1780,
         desc="Old oaks and towering conifers above Carlingford Lough; the Kodak Corner viewpoint is the money shot. Forest Service land — be discreet.",
         src=["https://outdoorscott.com/wild-camping-northern-ireland/"],
         hike_km=2.0),
    dict(name="Murlough Bay", county="Antrim", type="coast", access="hike", lat=55.2110, lng=-6.1450,
         desc="The Causeway Coast's hidden amphitheatre below Fair Head — Scotland floats on the horizon. Park at the Casement memorial and walk down.",
         src=["https://outdoorscott.com/wild-camping-northern-ireland/"],
         hike_km=1.2),
    dict(name="Benone Beach", county="Derry", type="beach", access="walk", lat=55.1680, lng=-6.8970,
         desc="Seven miles of hard golden sand under Binevenagh's cliffs. Pitch between the Martello tower and the tourist complex; Mussenden Temple up the strand.",
         src=["https://outdoorscott.com/wild-camping-northern-ireland/"],
         hike_km=0.6),
    dict(name="Lower Lough Erne (canoe trail)", county="Fermanagh", type="lake", access="hike", lat=54.4830, lng=-7.8700,
         desc="Island-hopping on the Lough Erne Canoe Trail — wooded islands and shore camps under the Cliffs of Magho. Best reached by paddle.",
         src=["https://outdoorscott.com/wild-camping-northern-ireland/"],
         hike_km=1.0),
    dict(name="Sperrins – Sawel Mountain", county="Tyrone", type="mountain", access="hike", lat=54.8210, lng=-7.0370,
         desc="The emptiest hills in the north — bog, big skies and some of Ireland's darkest stars over the Glenelly valley. People camp here often and meet no one.",
         src=["https://outdoorscott.com/wild-camping-northern-ireland/", "https://www.reddit.com/r/northernireland/comments/1mev0gb/wild_camping_spots/"],
         hike_km=3.0),
    dict(name="Lough Neagh – Ballyronan Wood", county="Derry", type="lake", access="walk", lat=54.7230, lng=-6.5680,
         desc="Waterside woodland on the biggest lake in these islands. Sunrise over the water and world-class birdlife; all shoreline is private, so ask around.",
         src=["https://outdoorscott.com/wild-camping-northern-ireland/"],
         hike_km=0.5),
    # ---- DONEGAL (bonus from NI thread) ----
    dict(name="Derrybeg dunes (Gweedore)", county="Donegal", type="beach", access="walk", lat=55.0740, lng=-8.3050,
         desc="Dunes on the Gweedore shore where locals have camped for generations — Milky Way skies, with the golf clubhouse bar a 15-minute walk away.",
         src=["https://www.reddit.com/r/northernireland/comments/1mev0gb/wild_camping_spots/"],
         hike_km=0.5),
]
